version: '3'
services:
  # mongo:
  #   image: mongo
  #   restart: on-failure
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: password

  # Mysql
  mysql:
    # use this for mac
    platform: linux/amd64
    image: mysql:8.0.26

    # use this for linux
    # platform: linux/x86_64
    # image: mysql:8.0.16

    # ======================= #
    restart: on-failure
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - "./storage/mysql/scripts:/docker-entrypoint-initdb.d"
      - "./storage/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gg_project
      MYSQL_TCP_PORT: 3306

  # Redis
  redis:
    image: redis:6
    restart: on-failure
    entrypoint:
      - "redis-server"
    volumes:
      - "./storage/redis/conf:/usr/lib/redis/conf"
      - "./storage/redis/modules:/usr/lib/redis/modules"
      - "./storage/redis/data:/data"
    ports:
      - "6379:6379"

  # elasticsearch :
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
  #   ports:
  #     - "9201:9200"
  #   environment:
  #       - discovery.type=single-node
  #       - cluster.name=elasticsearch
  #   volumes:
  #       - ./storage/es/data:/usr/share/elasticsearch/data
